title: Platero y yo ~ Juan Ramón Jimenez
description: Proyecto inspirado en la novela de Juan Ramón Jimenez ~ "Platero y yo", en el que se usa la librería de Phaser 3.
logo: /images/adaptacion.png
show_downloads: true
theme: jekyll-theme-minimal