title: Platero y yo, Generation Games (GG)
description: Proyecto inspirado en "Platero y yo" novela de Juan Ramón Jimenez
logo: /assets/img/adaptacion.png
show_downloads: false
theme: jekyll-theme-minimal